import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import PomodoroComponent from "../components/pomodoro";
import { useAppContext } from "../context/state";

const Pomodoro: NextPage = () => {
  const { theme }: any = useAppContext();

  return (
    <div className={`app-container ${theme} pomodoro-app-container`}>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <PomodoroComponent />
      </main>
    </div>
  );
};

export default Pomodoro;
