import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import PomodoroComponent from "../components/pomodoro";

const Pomodoro: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PomodoroComponent />
      </main>
    </div>
  );
};

export default Pomodoro;
